### ISSUE TITLE
Error in search after disable OR uninstall module

### ISSUE THREAD

**Issue by acs-ferreira** [staxDB/humhub-modules-announcements#49]
```
Error: Class 'humhub\modules\announcements\models\Announcement' not found in /public/protected/humhub/modules/search/libs/SearchResultSet.php:55
Stack trace:
#0 /public/protected/humhub/modules/search/controllers/SearchController.php(96): humhub\modules\search\libs\SearchResultSet->getResultInstances()
#1 [internal function]: humhub\modules\search\controllers\SearchController->actionIndex()
#2 /public/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#3 /public/protected/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#4 /public/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('index', Array)
#5 /public/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('search/search/i...', Array)
#6 /public/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(humhub\components\Request))
#7 /public/index.php(24): yii\base\Application->run()
#8 {main} 
```

**Comment by staxDB** [comment]
By disable or uninstall you mean disable the module in the specific space or globally?

**Comment by acs-ferreira** [comment]
Globally in modules administration.

**Comment by staxDB** [comment]
Okay, thanks for the information, I'll investigate this case.
By the way: How did you get HH v 1.3.4? In my local test environment v1.3.2 is shown as latest version.

**Comment by acs-ferreira** [comment]
Yeah, just a typo. 1.3.2 :smile:

**Comment by staxDB** [comment]
I can't reproduce this error..
If the module is gloablly disabled, the [`disable`-function](https://github.com/staxDB/humhub-modules-announcements/blob/acd75db5f51a63dfd97149f41624d9c284321a47/Module.php#L39) in `Module.php` will be called. There, all announcements will be automatically deleted. If an announcements gets deleted, the [`beforeDelete()`-function](https://github.com/staxDB/humhub-modules-announcements/blob/acd75db5f51a63dfd97149f41624d9c284321a47/models/Announcement.php#L386) will be called, which also deletes the entries in the announcement_user table...
If an module gets disabled, the tables created by this module should be empty but still exists. If the module gets deleted, the tables should be deleted too!

**Comment by staxDB** [comment]
@acs-ferreira does this error still exist?
